openapi: 3.0.1

info:
  title: ms-banking-purchases-api
  description: API for ms-banking-purchases
  version: 1.0.0
servers:
  - url: https://localhost:8093
tags:
  - name: ms-banking-purchases-api
    description: API for ms-banking-purchases
paths:
  /purchases:
    get:
      summary: Retrieve all purchases
      operationId: retrieveAllPurchases
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Purchases'
    post:
      summary: Save new purchase
      operationId: savePurchase
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseDTO'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PurchaseDTO"
    put:
      summary: Update an existing purchase
      operationId: updatePurchase
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PurchaseDTO"
  /purchases/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: purchase ID
        schema:
          type: string
    get:
      summary: Retrieve a purchase
      operationId: retrievePurchase
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PurchaseDTO"
    delete:
      summary: Delete a purchase
      operationId: deletePurchase
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PurchaseDTO"
  /purchases/customer/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: customer ID
        schema:
          type: string
    get:
      summary: Retrieve customer purchases
      operationId: retrieveCustomerPurchases
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Purchases'

components:
  schemas:
    Purchases:
      type: array
      items:
        $ref: "#/components/schemas/PurchaseDTO"
    PurchaseDTO:
      type: object
      properties:
        id:
          type: string
        customerId:
          type: string
        customerType:
          type: string
        customerName:
          type: string
        productId:
          type: string
        productType:
          type: string
        productCategory:
          type: string
        createdAt:
          type: string
        state:
          type: string
        accountNo:
          type: string
        balance:
          type: number
          format: double
        hasMaintenanceCommission:
          type: boolean
        maintenanceCommissionPercentage:
          type: number
          format: double
        hasMonthTransactionLimitQty:
          type: boolean
        monthTransactionLimitQty:
          type: integer
        maxCreditsQuantityAllowed:
          type: integer
        creditAmountLimit:
          type: number
          format: double
        customerCurrentMonthTransactionsMade:
          type: integer
      required:
        - id
        - customerId
        - productId